# =============================================================================
# 10-remove-files.ps1 — Remove files written into the project root by step 3
# =============================================================================
# Removes:
#   • static/staticwebapp.config.json
#   • api/  (entire GetRoles function directory)
#   • .github/workflows/azure-static-web-apps-deploy.yml
#   • swa-cli.config.json  (if generated by step 4)
#
# Does NOT touch any Evidence.dev source files (pages/, sources/, etc.).
# Idempotency: silently skips any file/directory that no longer exists.
# =============================================================================
param(
    [string]$EnvFile = "$PSScriptRoot\..\.env",
    [switch]$Force   # Skip per-item confirmation prompts
)

. "$PSScriptRoot\helpers.ps1"
Import-EnvFile -Path (Resolve-Path $EnvFile)

Write-Banner "Teardown Step 10 — Remove Generated Project Files"

# ── Resolve project root ──────────────────────────────────────────────────────
$deployDir   = $PSScriptRoot | Split-Path -Parent
$projectRoot = (Resolve-Path "$deployDir\..").Path

$projectRootOverride = Get-EnvOrDefault 'EVIDENCE_PROJECT_ROOT' ''
if ($projectRootOverride -and $projectRootOverride -ne '..') {
    if (Test-Path $projectRootOverride) {
        $projectRoot = (Resolve-Path $projectRootOverride).Path
    }
}

Write-Info "Project root : $projectRoot"

# ── Define targets ────────────────────────────────────────────────────────────
$targets = @(
    @{
        Path        = "$projectRoot\static\staticwebapp.config.json"
        Description = "SWA auth/route configuration"
        IsDir       = $false
    },
    @{
        Path        = "$projectRoot\api"
        Description = "GetRoles Azure Function directory"
        IsDir       = $true
    },
    @{
        Path        = "$projectRoot\.github\workflows\azure-static-web-apps-deploy.yml"
        Description = "GitHub Actions deployment workflow"
        IsDir       = $false
    },
    @{
        Path        = "$projectRoot\swa-cli.config.json"
        Description = "SWA CLI config (if generated)"
        IsDir       = $false
    }
)

# ── Print manifest of what will be removed ────────────────────────────────────
Write-Step "Files and directories to remove"
$found = $targets | Where-Object { Test-Path $_.Path }
$missing = $targets | Where-Object { -not (Test-Path $_.Path) }

foreach ($t in $found) {
    $label = if ($t.IsDir) { "[dir] " } else { "[file]" }
    Write-Host "   $label  $($t.Path)" -ForegroundColor Yellow
    Write-Info "          ($($t.Description))"
}
foreach ($t in $missing) {
    Write-Info "   [skip]  $($t.Path) — not found"
}

if ($found.Count -eq 0) {
    Write-OK "No generated files found — nothing to remove."
    return
}

# ── Confirm ───────────────────────────────────────────────────────────────────
if (-not $Force) {
    Write-Host ""
    $ok = Confirm-Step "Remove $($found.Count) item(s) listed above?"
    if (-not $ok) { Write-Warn "Skipped by user."; return }
}

# ── Remove ────────────────────────────────────────────────────────────────────
$removed = 0
foreach ($t in $found) {
    try {
        if ($t.IsDir) {
            Remove-Item -Path $t.Path -Recurse -Force
            Write-OK "Removed dir : $($t.Path)"
        } else {
            Remove-Item -Path $t.Path -Force
            Write-OK "Removed file: $($t.Path)"
        }
        $removed++
    } catch {
        Write-Warn "Could not remove $($t.Path): $_"
    }
}

# ── Clean up empty parent directories ────────────────────────────────────────
$parentsToPrune = @(
    "$projectRoot\static",
    "$projectRoot\.github\workflows",
    "$projectRoot\.github"
)
foreach ($dir in $parentsToPrune) {
    if ((Test-Path $dir) -and -not (Get-ChildItem $dir -Force)) {
        Remove-Item $dir -Force | Out-Null
        Write-Info "Pruned empty directory: $dir"
    }
}

Write-Host ""
Write-OK "$removed item(s) removed."
Write-Info "Evidence.dev source files (pages/, sources/) were not touched."
